kind: pipeline
type: docker
name: CI

steps:
  - name: install
    image: node:13
    commands:
      - yarn
    volumes:
      - name: docker
        path: /var/run/docker.sock
  - name: test
    image: node:13
    commands:
      - yarn test:ci
    volumes:
      - name: docker
        path: /var/run/docker.sock
  - name: lint
    image: node:13
    commands:
      - yarn lint
    volumes:
      - name: docker
        path: /var/run/docker.sock

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
