kind: pipeline
type: docker
name: CI

steps:
  - name: install
    image: node:13
    commands:
      - yarn
    volumes:
      - name: docker
        path: /var/run/docker.sock
  - name: test
    image: node:13
    commands:
      - yarn test:ci
    volumes:
      - name: docker
        path: /var/run/docker.sock
  - name: lint
    image: node:13
    commands:
      - yarn lint
    volumes:
      - name: docker
        path: /var/run/docker.sock

kind: pipeline
name: CD

steps:
  - name: build
    image: docker
    commands:
      - docker build . -t cda-user-api:latest
    volumes:
      - name: docker
        path: /var/run/docker.sock
  - name: deploy-preview
    image: docker/compose:1.24.1
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - docker-compose -p cda-user-api up -d preview
    depends_on:
      - build
  - name: deploy-production
    image: docker/compose:1.24.1
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - docker-compose -p cda-user-api up -d production
    depends_on:
      - build
    when:
      branch:
        - master

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock


volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
