kind: pipeline
type: docker
name: CI

steps:
  - name: build
    image: node:10
    commands:
      - yarn
      - yarn build
    volumes:
      - name: docker
        path: /var/run/docker.sock
    depends_on:
      - clone
  - name: test
    image: node:10
    commands:
      - yarn test
    volumes:
      - name: docker
        path: /var/run/docker.sock
    depends_on:
      - clone

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
