---
kind: pipeline
type: docker
name: CI

steps:
  - name: install
    image: node:13
    commands:
      - yarn --network-timeout 1000000
    volumes:
      - name: docker
        path: /var/run/docker.sock
  - name: test
    image: node:13
    environment:
      CODECOV_TOKEN:
        from_secret: CODECOV_TOKEN
    commands:
      - yarn test:ci
    volumes:
      - name: docker
        path: /var/run/docker.sock
  - name: lint
    image: node:13
    commands:
      - yarn lint
    volumes:
      - name: docker
        path: /var/run/docker.sock

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

---
kind: pipeline
type: docker
name: CD

steps:
  - name: build
    image: docker
    environment:
      MONGO_URL:
        from_secret: MONGO_URL
      JWT_SECRET:
        from_secret: JWT_SECRET
      JWT_EXPIRATION:
        from_secret: JWT_EXPIRATION
    commands:
      - docker build . -t cda-user-api:latest
    volumes:
      - name: docker
        path: /var/run/docker.sock
  - name: deploy-preview
    image: docker/compose:1.24.1
    environment:
      MONGO_URL:
        from_secret: MONGO_URL
      JWT_SECRET:
        from_secret: JWT_SECRET
      JWT_EXPIRATION:
        from_secret: JWT_EXPIRATION
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - docker-compose -p cda-user-api up -d preview
    depends_on:
      - build
  - name: deploy-production
    image: docker/compose:1.24.1
    environment:
      MONGO_URL:
        from_secret: MONGO_URL
      JWT_SECRET:
        from_secret: JWT_SECRET
      JWT_EXPIRATION:
        from_secret: JWT_EXPIRATION
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - docker-compose -p cda-user-api up -d production
    depends_on:
      - build
    when:
      branch:
        - master

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
