kind: pipeline
type: docker
name: CI

steps:
  - name: install
    image: node:10
    commands:
      - yarn
    volumes:
      - name: docker
        path: /var/run/docker.sock
  - name: build
    image: node:10
    commands:
      - yarn build
    volumes:
      - name: docker
        path: /var/run/docker.sock
  - name: test
    image: node:10
    commands:
      - yarn test
    volumes:
      - name: docker
        path: /var/run/docker.sock

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
