version: '3'
services:
  preview:
    build: .
    image: cda-user-api:latest
    restart: always
    labels:
      - "traefik.frontend.rule=Host:auth.cda.cchampou.me"
      - "traefik.backend.port=3000"
      - "traefik.enable=true"
      - "traefik.docker.network=layko_layko_net"
    environment:
      NODE_ENV: staging
      MONGO_URL: $MONGO_URL
      JWT_SECRET: $JWT_SECRET
      JWT_EXPIRATION: $JWT_EXPIRATION
  production:
    build: .
    image: cda-user-api:latest
    restart: always
    labels:
      - "traefik.frontend.rule=Host:auth.parrainage.confidencesdabeilles.fr"
      - "traefik.backend.port=3000"
      - "traefik.enable=true"
      - "traefik.docker.network=layko_layko_net"
    environment:
      NODE_ENV: production
      MONGO_URL: $MONGO_URL
      JWT_SECRET: $JWT_SECRET
      JWT_EXPIRATION: $JWT_EXPIRATION
networks:
  default:
    external:
      name: layko_layko_net
